import GameStore from '../stores/GameStore';

const { color } = GameStore;

module.exports = [
  //Blank Tile
  [{ display: 'block' }],
  //Barrels
  [
    {
      position: 'absolute',
      bottom: '10%',
      left: '20%',
      height: '50%',
      width: '30%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderTopColor: 'transparent',
      borderBottomLeftRadius: 2,
      borderBottomRightRadius: 2,
    },
    {
      position: 'absolute',
      top: '37%',
      left: '20%',
      height: '8%',
      width: '30%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderRadius: 50,
    },
    {
      position: 'absolute',
      left: '20%',
      bottom: '15%',
      height: '5%',
      width: '30%',
      backgroundColor: color.primary,
      borderBottomColor: 'transparent',
    },
    {
      position: 'absolute',
      left: '20%',
      bottom: '47%',
      height: '5%',
      width: '30%',
      backgroundColor: color.primary,
      borderBottomColor: 'transparent',
    },
    {
      position: 'absolute',
      bottom: '20%',
      right: '18%',
      height: '50%',
      width: '30%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderTopColor: 'transparent',
      borderBottomLeftRadius: 2,
      borderBottomRightRadius: 2,
    },
    {
      position: 'absolute',
      top: '26%',
      right: '18%',
      height: '8%',
      width: '30%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderRadius: 50,
    },
    {
      position: 'absolute',
      right: '18%',
      top: '38%',
      height: '5%',
      width: '30%',
      backgroundColor: color.primary,
      borderBottomColor: 'transparent',
    },
    {
      position: 'absolute',
      right: '18%',
      bottom: '25%',
      height: '5%',
      width: '30%',
      backgroundColor: color.primary,
      borderBottomColor: 'transparent',
    },
    {
      position: 'absolute',
      top: '18%',
      left: '25%',
      height: '20%',
      width: '28%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderTopColor: 'transparent',
      borderBottomColor: 'transparent',
    },
    {
      position: 'absolute',
      top: '17%',
      left: '25%',
      height: '8%',
      width: '28%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderRadius: 50,
    },
    {
      position: 'absolute',
      top: '28%',
      left: '25%',
      height: '5%',
      width: '28%',
      backgroundColor: color.primary,
      borderBottomColor: 'transparent',
    },
  ],
  //Table and Chairs
  [
    {
      position: 'absolute',
      top: '25%',
      left: '25%',
      height: '35%',
      width: '35%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderRadius: 50,
    },
    {
      position: 'absolute',
      bottom: '20%',
      right: '10%',
      height: '20%',
      width: '20%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      transform: [{ rotate: '25deg' }],
    },
    {
      position: 'absolute',
      top: '10%',
      right: '10%',
      height: '20%',
      width: '20%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      transform: [{ rotate: '-10deg' }],
    },
    {
      position: 'absolute',
      bottom: '10%',
      left: '15%',
      height: '20%',
      width: '20%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      transform: [{ rotate: '10deg' }],
    },
  ],
  //Table and Chairs
  [
    {
      position: 'absolute',
      bottom: '20%',
      right: '20%',
      height: '35%',
      width: '35%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderRadius: 50,
    },
    {
      position: 'absolute',
      top: '10%',
      right: '10%',
      height: '20%',
      width: '20%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      transform: [{ rotate: '5deg' }],
    },
    {
      position: 'absolute',
      top: '30%',
      left: '15%',
      height: '20%',
      width: '20%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      transform: [{ rotate: '-10deg' }],
    },
  ],
  //Basic Torch (N)
  [
    {
      position: 'absolute',
      top: '35%',
      height: '20%',
      width: '12%',
      backgroundColor: color.primary,
      borderTopLeftRadius: 100,
      borderTopRightRadius: 0,
      borderBottomLeftRadius: 10,
      borderBottomRightRadius: 100,
      transform: [{ rotate: '-30deg' }],
    },
    {
      position: 'absolute',
      right: '45%',
      top: '10%',
      height: '20%',
      width: '5%',
      backgroundColor: color.primary,
      borderRadius: 50,
      transform: [{ rotate: '-20deg' }],
    },
    {
      position: 'absolute',
      left: '45%',
      top: '10%',
      height: '20%',
      width: '5%',
      backgroundColor: color.primary,
      borderRadius: 50,
      transform: [{ rotate: '20deg' }],
    },
  ],
  //Basic Torch (E)
  [
    {
      position: 'absolute',
      right: '10%',
      top: '20%',
      height: '20%',
      width: '12%',
      backgroundColor: color.primary,
      borderTopLeftRadius: 100,
      borderTopRightRadius: 0,
      borderBottomLeftRadius: 10,
      borderBottomRightRadius: 100,
      transform: [{ rotate: '150deg' }],
    },
    {
      position: 'absolute',
      right: '10%',
      bottom: '25%',
      height: '25%',
      width: '5%',
      backgroundColor: color.primary,
      borderRadius: 50,
      transform: [{ rotate: '160deg' }],
    },
  ],
  //Basic Torch (S)
  [
    {
      position: 'absolute',
      bottom: '35%',
      height: '20%',
      width: '12%',
      backgroundColor: color.primary,
      borderTopLeftRadius: 100,
      borderTopRightRadius: 0,
      borderBottomLeftRadius: 10,
      borderBottomRightRadius: 100,
      transform: [{ rotate: '150deg' }],
    },
    {
      position: 'absolute',
      right: '45%',
      bottom: '10%',
      height: '20%',
      width: '5%',
      backgroundColor: color.primary,
      borderRadius: 50,
      transform: [{ rotate: '200deg' }],
    },
    {
      position: 'absolute',
      left: '45%',
      bottom: '10%',
      height: '20%',
      width: '5%',
      backgroundColor: color.primary,
      borderRadius: 50,
      transform: [{ rotate: '-200deg' }],
    },
  ],
  //Basic Torch (W)
  [
    {
      position: 'absolute',
      left: '10%',
      top: '20%',
      height: '20%',
      width: '12%',
      backgroundColor: color.primary,
      borderTopLeftRadius: 100,
      borderTopRightRadius: 0,
      borderBottomLeftRadius: 10,
      borderBottomRightRadius: 100,
      transform: [{ rotate: '-30deg' }],
    },
    {
      position: 'absolute',
      left: '10%',
      bottom: '25%',
      height: '25%',
      width: '5%',
      backgroundColor: color.primary,
      borderRadius: 50,
      transform: [{ rotate: '20deg' }],
    },
  ],
];
