import GameStore from '../stores/GameStore';

const { color } = GameStore;

module.exports = [
  //Blank Tile
  [{ display: 'block' }],
  //Basic Long Door Left (E/W)
  [
    {
      position: 'absolute',
      right: '50%',
      height: '20%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      height: '7%',
      width: '100%',
      backgroundColor: color.primary,
    },
  ],
  //Basic Long Door Middle (E/W)
  [
    {
      position: 'absolute',
      height: '7%',
      width: '100%',
      backgroundColor: color.primary,
    },
  ],
  //Basic Long Door Right (E/W)
  [
    {
      position: 'absolute',
      height: '7%',
      width: '100%',
      backgroundColor: color.primary,
    },
    {
      position: 'absolute',
      left: '50%',
      height: '20%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
  ],
  //Basic Corner (S/E)
  [
    {
      position: 'absolute',
      top: '42%',
      height: '100%',
      width: '20%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      left: '42%',
      height: '20%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
  ],
  //Basic Wall (E/W)
  [
    {
      height: '20%',
      width: '100%',
      backgroundColor: color.primary,
    },
  ],
  //Basic Corner (S/W)
  [
    {
      position: 'absolute',
      top: '42%',
      height: '100%',
      width: '20%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      right: '42%',
      height: '20%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
  ],
  //Basic Long Door Top (N/S)
  [
    {
      position: 'absolute',
      bottom: '50%',
      height: '100%',
      width: '20%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      height: '100%',
      width: '7%',
      backgroundColor: color.primary,
    },
  ],
  //Basic Wall (N/S)
  [
    {
      height: '100%',
      width: '20%',
      backgroundColor: color.primary,
    },
  ],
  //Blank Tile
  [{ display: 'block' }],
  //Basic Wall (N/S)
  [
    {
      height: '100%',
      width: '20%',
      backgroundColor: color.primary,
    },
  ],
  //Basic Long Door Middle (N/S)
  [
    {
      position: 'absolute',
      height: '100%',
      width: '7%',
      backgroundColor: color.primary,
    },
  ],
  //Basic Corner (N/E)
  [
    {
      position: 'absolute',
      bottom: '42%',
      height: '100%',
      width: '20%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      left: '42%',
      height: '20%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
  ],
  //Basic Wall (E/W)
  [
    {
      height: '20%',
      width: '100%',
      backgroundColor: color.primary,
    },
  ],
  //Basic Corner (N/W)
  [
    {
      position: 'absolute',
      bottom: '42%',
      height: '100%',
      width: '20%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      right: '42%',
      height: '20%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
  ],
  //Basic Long Door Bottom (N/S)
  [
    {
      position: 'absolute',
      height: '100%',
      width: '7%',
      backgroundColor: color.primary,
    },
    {
      position: 'absolute',
      top: '50%',
      height: '100%',
      width: '20%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
  ],
  //Basic T (E)
  [
    {
      position: 'absolute',
      left: '40%',
      height: '20%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      height: '100%',
      width: '20%',
      backgroundColor: color.primary,
    },
  ],
  //Basic T (S)
  [
    {
      position: 'absolute',
      top: '40%',
      height: '100%',
      width: '20%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      height: '20%',
      width: '100%',
      backgroundColor: color.primary,
    },
  ],
  //Basic T (N)
  [
    {
      position: 'absolute',
      bottom: '40%',
      height: '100%',
      width: '20%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      height: '20%',
      width: '100%',
      backgroundColor: color.primary,
    },
  ],
  //Basic T (W)
  [
    {
      position: 'absolute',
      right: '40%',
      height: '20%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      height: '100%',
      width: '20%',
      backgroundColor: color.primary,
    },
  ],
  //Basic +
  [
    {
      position: 'absolute',
      height: '20%',
      width: '100%',
      backgroundColor: color.primary,
    },
    {
      position: 'absolute',
      height: '100%',
      width: '20%',
      backgroundColor: color.primary,
    },
  ],
  //Basic Door (N/S)
  [
    {
      position: 'absolute',
      bottom: '75%',
      height: '100%',
      width: '20%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      height: '100%',
      width: '7%',
      backgroundColor: color.primary,
    },
    {
      position: 'absolute',
      top: '75%',
      height: '100%',
      width: '20%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
  ],
  //Basic Door (E/W)
  [
    {
      position: 'absolute',
      right: '75%',
      height: '20%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      height: '7%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      left: '75%',
      height: '20%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
  ],
  //Basic Tree
  [
    {
      position: 'absolute',
      bottom: '50%',
      width: 0,
      height: 0,
      borderStyle: 'solid',
      borderLeftWidth: '4%',
      borderRightWidth: '4%',
      borderBottomWidth: '8%',
      borderLeftColor: 'transparent',
      borderRightColor: 'transparent',
      borderBottomColor: color.primary,
    },
    {
      position: 'absolute',
      bottom: '25%',
      width: 0,
      height: 0,
      borderStyle: 'solid',
      borderLeftWidth: '5%',
      borderRightWidth: '5%',
      borderBottomWidth: '10%',
      borderLeftColor: 'transparent',
      borderRightColor: 'transparent',
      borderBottomColor: color.primary,
    },
  ],
  //Water Shore Corner (N/W)
  [
    {
      position: 'absolute',
      top: '47%',
      height: '100%',
      width: '10%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      left: '47%',
      height: '10%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      bottom: '10%',
      right: '7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      bottom: '10%',
      right: '-7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
  ],
  //Water Shore (W/E)
  [
    {
      height: '10%',
      width: '100%',
      backgroundColor: color.primary,
    },
    {
      position: 'absolute',
      bottom: '10%',
      left: '-7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      bottom: '10%',
      left: '7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      bottom: '10%',
      left: '22.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      bottom: '10%',
      right: '22.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      bottom: '10%',
      right: '7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      bottom: '10%',
      right: '-7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
  ],
  //Water Shore Corner (N/E)
  [
    {
      position: 'absolute',
      top: '47%',
      height: '100%',
      width: '10%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      right: '47%',
      height: '10%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      bottom: '10%',
      left: '-7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      bottom: '10%',
      left: '7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
  ],
  //Basic Tree 2
  [
    {
      position: 'absolute',
      bottom: '60%',
      width: 0,
      height: 0,
      borderStyle: 'solid',
      borderLeftWidth: '4%',
      borderRightWidth: '4%',
      borderBottomWidth: '8%',
      borderLeftColor: 'transparent',
      borderRightColor: 'transparent',
      borderBottomColor: color.primary,
    },
    {
      position: 'absolute',
      bottom: '40%',
      width: 0,
      height: 0,
      borderStyle: 'solid',
      borderLeftWidth: '5%',
      borderRightWidth: '5%',
      borderBottomWidth: '10%',
      borderLeftColor: 'transparent',
      borderRightColor: 'transparent',
      borderBottomColor: color.primary,
    },
    {
      position: 'absolute',
      bottom: '25%',
      width: '5%',
      height: '50%',
      backgroundColor: color.primary,
    },
  ],
  //Water Shore (N/S/W)
  [
    {
      height: '100%',
      width: '10%',
      backgroundColor: color.primary,
    },
    {
      position: 'absolute',
      top: '20%',
      right: '7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      top: '20%',
      right: '-7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      bottom: '20%',
      right: '7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      bottom: '20%',
      right: '-7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
  ],
  //Water Tile
  [
    {
      position: 'absolute',
      top: '20%',
      left: '-7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      top: '20%',
      left: '7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      top: '20%',
      left: '22.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      top: '20%',
      right: '22.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      top: '20%',
      right: '7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      top: '20%',
      right: '-7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    // *** separator ***
    {
      position: 'absolute',
      bottom: '20%',
      left: '-7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      bottom: '20%',
      left: '7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      bottom: '20%',
      left: '22.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      bottom: '20%',
      right: '22.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      bottom: '20%',
      right: '7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      bottom: '20%',
      right: '-7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
  ],
  //Water Shore (N/S/E)
  [
    {
      height: '100%',
      width: '10%',
      backgroundColor: color.primary,
    },
    {
      position: 'absolute',
      top: '20%',
      left: '-7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      top: '20%',
      left: '7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      bottom: '20%',
      left: '-7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      bottom: '20%',
      left: '7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
  ],
  //Basic Grass
  [
    {
      position: 'absolute',
      borderRadius: 1,
      left: '30%',
      bottom: '25%',
      width: '4%',
      height: '20%',
      backgroundColor: color.primary,
      transform: [{ rotate: '-20deg' }],
    },
    {
      position: 'absolute',
      borderRadius: 1,
      bottom: '25%',
      width: '5%',
      height: '30%',
      backgroundColor: color.primary,
    },
    {
      position: 'absolute',
      borderRadius: 1,
      right: '30%',
      bottom: '25%',
      width: '4%',
      height: '20%',
      backgroundColor: color.primary,
      transform: [{ rotate: '20deg' }],
    },
  ],
  //Water Shore Corner (S/W)
  [
    {
      position: 'absolute',
      bottom: '47%',
      height: '100%',
      width: '10%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      left: '47%',
      height: '10%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '10%',
      right: '7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      top: '10%',
      right: '-7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
  ],
  //Water Shore (W/E)
  [
    {
      height: '10%',
      width: '100%',
      backgroundColor: color.primary,
    },
    {
      position: 'absolute',
      top: '10%',
      left: '-7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      top: '10%',
      left: '7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      top: '10%',
      left: '22.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      top: '10%',
      right: '22.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      top: '10%',
      right: '7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      top: '10%',
      right: '-7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
  ],
  //Water Shore Corner (N/E)
  [
    {
      position: 'absolute',
      bottom: '47%',
      height: '100%',
      width: '10%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      right: '47%',
      height: '10%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '10%',
      left: '-7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderTopColor: 'transparent',
      borderRightColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
    {
      position: 'absolute',
      top: '10%',
      left: '7.5%',
      height: '15%',
      width: '15%',
      borderColor: color.primary,
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
      borderStyle: 'solid',
      borderWidth: 0.5,
      borderRadius: 1,
      transform: [{ rotate: '-45deg' }],
    },
  ],
  //Item
  [
    {
      position: 'absolute',
      bottom: '15%',
      left: '20%',
      height: '40%',
      width: '40%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      bottom: '33%',
      left: '41%',
      height: '10%',
      width: '15%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderRadius: 1,
      transform: [{ rotate: '50deg' }],
    },
    {
      position: 'absolute',
      bottom: '46%',
      left: '49%',
      width: '14%',
      height: '23%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderBottomColor: 'transparent',
      transform: [{ rotate: '35deg' }],
    },
    {
      position: 'absolute',
      top: '25%',
      right: '22%',
      height: '10%',
      width: '25%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderRadius: 1,
      transform: [{ rotate: '35deg' }],
    },
  ],
  //Cart Left
  [
    {
      position: 'absolute',
      bottom: '5%',
      left: '40%',
      height: '30%',
      width: '30%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      bottom: '20%',
      left: '30%',
      height: '25%',
      width: '100%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderRadius: 0.1,
    },
    {
      position: 'absolute',
      bottom: '30%',
      left: '30%',
      height: 1,
      width: '100%',
      backgroundColor: color.primary,
    },
    {
      position: 'absolute',
      top: '7%',
      left: '30%',
      height: '50%',
      width: '100%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderTopLeftRadius: 8,
    },
    {
      position: 'absolute',
      top: '7%',
      left: '50%',
      height: '50%',
      width: '100%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderTopLeftRadius: 15,
    },
    {
      position: 'absolute',
      top: '7%',
      left: '75%',
      height: '50%',
      width: '100%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderTopLeftRadius: 15,
    },
  ],
  //Cart Right
  [
    {
      position: 'absolute',
      bottom: '5%',
      right: '40%',
      height: '30%',
      width: '30%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      bottom: '20%',
      right: '30%',
      height: '25%',
      width: '100%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderRadius: 0.2,
    },
    {
      position: 'absolute',
      bottom: '30%',
      right: '30%',
      height: 1,
      width: '100%',
      backgroundColor: color.primary,
    },
    {
      position: 'absolute',
      top: '7%',
      right: '50%',
      height: '50%',
      width: '100%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderTopRightRadius: 5,
    },
    {
      position: 'absolute',
      top: '3%',
      left: '35%',
      height: '54%',
      width: '100%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderTopLeftRadius: 15,
      borderRightColor: 'transparent',
      borderBottomColor: 'transparent',
      borderTopColor: 'transparent',
    },
  ],
  //City Wall Opening Right (E/W)
  [
    {
      position: 'absolute',
      left: '50%',
      height: '30%',
      width: '100%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 2,
      borderRadius: 1,
    },
  ],
  //City Wall Opening Left (E/W)
  [
    {
      position: 'absolute',
      right: '50%',
      height: '30%',
      width: '100%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 2,
      borderRadius: 1,
    },
  ],
  // ***************************************************************************************
  //City Wall Corner (N/W)
  [
    {
      position: 'absolute',
      top: '35%',
      left: '35%',
      height: '100%',
      width: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '35%',
      left: '35%',
      height: '5%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '60%',
      left: '60%',
      height: '100%',
      width: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '60%',
      left: '60%',
      height: '5%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
  ],
  //City Wall (E/W)
  [
    {
      position: 'absolute',
      top: '35%',
      height: '5%',
      width: '100%',
      backgroundColor: color.primary,
    },
    {
      position: 'absolute',
      top: '60%',
      height: '5%',
      width: '100%',
      backgroundColor: color.primary,
    },
  ],
  //City Corner (N/E)
  [
    {
      position: 'absolute',
      top: '35%',
      right: '35%',
      height: '100%',
      width: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '35%',
      right: '35%',
      height: '5%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '60%',
      right: '60%',
      height: '100%',
      width: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '60%',
      right: '60%',
      height: '5%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
  ],
  //City Wall Opening Bottom (N/S)
  [
    {
      position: 'absolute',
      top: '50%',
      height: '100%',
      width: '30%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 2,
      borderRadius: 1,
    },
  ],
  //City Wall (N/S)
  [
    {
      position: 'absolute',
      left: '35%',
      height: '100%',
      width: '5%',
      backgroundColor: color.primary,
    },
    {
      position: 'absolute',
      left: '60%',
      height: '100%',
      width: '5%',
      backgroundColor: color.primary,
    },
  ],
  //Blank Tile
  [{ display: 'block' }],
  //City Wall (N/S)
  [
    {
      position: 'absolute',
      left: '35%',
      height: '100%',
      width: '5%',
      backgroundColor: color.primary,
    },
    {
      position: 'absolute',
      left: '60%',
      height: '100%',
      width: '5%',
      backgroundColor: color.primary,
    },
  ],
  //City Wall Opening Bottom (N/S)
  [
    {
      position: 'absolute',
      bottom: '50%',
      height: '100%',
      width: '30%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 2,
      borderRadius: 1,
    },
  ],
  //City Wall Corner (S/E)
  [
    {
      position: 'absolute',
      bottom: '35%',
      left: '35%',
      height: '100%',
      width: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      bottom: '35%',
      left: '35%',
      height: '5%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      bottom: '60%',
      left: '60%',
      height: '100%',
      width: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      bottom: '60%',
      left: '60%',
      height: '5%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
  ],
  //City Wall (E/W)
  [
    {
      position: 'absolute',
      bottom: '35%',
      height: '5%',
      width: '100%',
      backgroundColor: color.primary,
    },
    {
      position: 'absolute',
      bottom: '60%',
      height: '5%',
      width: '100%',
      backgroundColor: color.primary,
    },
  ],
  //City Corner (S/W)
  [
    {
      position: 'absolute',
      bottom: '35%',
      right: '35%',
      height: '100%',
      width: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      bottom: '35%',
      right: '35%',
      height: '5%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      bottom: '60%',
      right: '60%',
      height: '100%',
      width: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      bottom: '60%',
      right: '60%',
      height: '5%',
      width: '100%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
  ],
  //Treasure
  [
    {
      position: 'absolute',
      height: '60%',
      width: '80%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderRadius: 0.15,
    },
    {
      position: 'absolute',
      top: '40%',
      height: 1,
      width: '80%',
      backgroundColor: color.primary,
    },
    {
      position: 'absolute',
      top: '40%',
      height: '15%',
      width: '10%',
      borderColor: color.primary,
      borderStyle: 'solid',
      borderWidth: 1,
      borderRadius: 0.5,
    },
    {
      position: 'absolute',
      left: '25%',
      width: 1,
      height: '60%',
      backgroundColor: color.primary,
    },
    {
      position: 'absolute',
      left: '40%',
      width: 1,
      height: '60%',
      backgroundColor: color.primary,
    },
    {
      position: 'absolute',
      right: '25%',
      width: 1,
      height: '60%',
      backgroundColor: color.primary,
    },
    {
      position: 'absolute',
      right: '40%',
      width: 1,
      height: '60%',
      backgroundColor: color.primary,
    },
  ],
  //Edge Tile
  [
    {
      position: 'absolute',
      top: '5%',
      left: '5%',
      width: '5%',
      height: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '20%',
      left: '15%',
      width: '5%',
      height: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '30%',
      left: '5%',
      width: '5%',
      height: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '15%',
      left: '35%',
      width: '5%',
      height: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '70%',
      left: '80%',
      width: '5%',
      height: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '95%',
      left: '10%',
      width: '5%',
      height: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '5%',
      left: '5%',
      width: '5%',
      height: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '20%',
      left: '40%',
      width: '5%',
      height: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '75%',
      left: '55%',
      width: '5%',
      height: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '5%',
      left: '95%',
      width: '5%',
      height: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '15%',
      left: '85%',
      width: '5%',
      height: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '65%',
      left: '30%',
      width: '5%',
      height: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '30%',
      left: '65%',
      width: '5%',
      height: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '50%',
      left: '45%',
      width: '5%',
      height: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '90%',
      left: '65%',
      width: '5%',
      height: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
    {
      position: 'absolute',
      top: '45%',
      left: '95%',
      width: '5%',
      height: '5%',
      backgroundColor: color.primary,
      borderRadius: 1,
    },
  ],
];
